FROM node:25-alpine3.21 AS build

WORKDIR /app
COPY . .
RUN npm install -g @angular/cli
RUN npm i
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
