FROM maven:4.0.0-rc-5-amazoncorretto-17-al2023 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -Pprod -DskipTests

FROM amazoncorretto:17-al2023

WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
ENV SPRING_PROFILES_ACTIVE=prod
CMD ["java", "-jar", "app.jar"]
