spring:
  application:
    name: Todo App
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  docker:
    compose:
      file: "./dev/compose.yaml"
server:
  error:
    includeStacktrace: NEVER
